import { Data } from "./data";

export const DATA: Data[] = [
    { id: 0, brand: "BLACK COMME DES GARCONS", item: "プリーツシャツ", item_category: "シャツ", value: 25000, image: "../broken_image.png" },
    { id: 1, brand: "BLACK COMME DES GARCONS", item: "シワ加工バルーンパンツ", item_category: "パンツ", value: 35000, image: "../broken_image.png" },
    { id: 2, brand: ["BLACK COMME DES GARCONS", "NIKE"], item: "ナイトトラック", item_category: "シューズ", value: 20000, image: "../broken_image.png" },
    { id: 3, brand: "LAD MUSICIAN", item: "靴下", item_category: "レッグウェア", value: 2000, image: "../broken_image.png" },
    { id: 4, brand: "LAD MUSICIAN", item: "靴下", item_category: "レッグウェア", value: 2000, image: "../broken_image.png" },
    { id: 5, brand: "used", item: "バルーンパンツ", item_category: "パンツ", value: 8000, image: "../broken_image.png" },
    { id: 6, brand: "BLACK COMME DES GARCONS", item: "シワ加工シャツ", item_category: "シャツ", value: 20000, image: "../broken_image.png" },
    { id: 7, brand: "used", item: "ストレートリブパンツ", item_category: "パンツ", value: 10000, image: "../broken_image.png" },
    { id: 8, brand: "used", item: "ロングチェスターコート", item_category: "アウター", value: 25000, image: "../broken_image.png" },
    { id: 9, brand: "used", item: "チェスターコート", item_category: "アウター", value: 24000, image: "../broken_image.png" },
    { id: 10, brand: "ANREALAGE", item: "ボールシャツ", item_category: "シャツ", value: 24000, image: "../broken_image.png" },
    { id: 11, brand: "ANREALAGE", item: "トートバッグ", item_category: "バッグ", value: 4000, image: "../broken_image.png" },
    { id: 12, brand: "used", item: "チェックボアブルゾン", item_category: "アウター", value: 20000, image: "../broken_image.png" },
    { id: 13, brand: "LAD MUSICIAN", item: "スカートワイドパンツ", item_category: "パンツ", value: 35000, image: "../broken_image.png" },
    { id: 14, brand: "CHRISTIAN DADA", item: "KARAKUSA Buckle Leather Belt", item_category: "ベルト", value: 14000, image: "../broken_image.png" },
    { id: 15, brand: "DR.MARTENS", item: "ダブルバックルレザーシューズ", item_category: "シューズ", value: 12000, image: "../broken_image.png" },
    { id: 16, brand: "BLACK COMME DES GARCONS", item: "墨ぶち撒けシャツ", item_category: "シャツ", value: 25000, image: "../broken_image.png" },
    { id: 17, brand: "ISSEYMIYAKE", item: "チャイナシャツ", item_category: "シャツ", value: 20000, image: "../broken_image.png" },
    { id: 18, brand: "LANVIN", item: "ストレートトラウザーズ", item_category: "パンツ", value: 20000, image: "../broken_image.png" },
    { id: 19, brand: "COMME DES GARCONS HOMME DEUX", item: "スタッズシャツ", item_category: "シャツ", value: 24000, image: "../broken_image.png" },
    { id: 20, brand: "YOHJI YAMAMOTO", item: "バックパッチワークジャケット", item_category: "ジャケット", value: 40000, image: "../broken_image.png" },
    { id: 21, brand: "used", item: "ジップパンクブルゾン", item_category: "ジャケット", value: 16000, image: "../broken_image.png" },
    { id: 22, brand: "LAD MUSICIAN", item: "幾何学カットソー", item_category: "Tシャツ/カットソー", value: 10000, image: "../broken_image.png" },
    { id: 23, brand: "LAD MUSICIAN", item: "グラフィカルカットソー", item_category: "Tシャツ/カットソー", value: 15000, image: "../broken_image.png" },
    { id: 24, brand: "BLACK COMME DES GARCONS", item: "ジップトラウザーズ", item_category: "パンツ", value: 53000, image: "../broken_image.png" },
    { id: 25, brand: "JULIUS", item: "プリントハイネックカットソー", item_category: "Tシャツ/カットソー", value: 15000, image: "../broken_image.png" },
    { id: 26, brand: "Y-3", item: "ワイドカーゴパンツ", item_category: "パンツ", value: 20000, image: "../broken_image.png" },
    { id: 27, brand: "used", item: "オーバーサイズデニムジャケット", item_category: "ジャケット", value: 14000, image: "../broken_image.png" },
    { id: 28, brand: "RAF SIMONS", item: "プリントオーバーサイズシャツ", item_category: "シャツ", value: 39000, image: "../broken_image.png" },
    { id: 29, brand: "MOSCHINO", item: "プリントジャケット", item_category: "ジャケット", value: 30000, image: "../broken_image.png" },
    { id: 30, brand: "DIOR HOMME", item: "レースアップブーツ", item_category: "シューズ", value: 51000, image: "../broken_image.png" },
    { id: 31, brand: "CHRISTIAN DADA", item: "バケットハット", item_category: "ハット/キャップ", value: 16000, image: "../broken_image.png" },
    { id: 32, brand: "CHRISTIAN DADA", item: "ダウントレンチ", item_category: "アウター", value: 120000, image: "../broken_image.png" },
    { id: 33, brand: "VIKTOR&ROLF", item: "メガネ", item_category: "アイウェア", value: 53000, image: "../broken_image.png" },
    { id: 34, brand: "used", item: "リアルレザーパンツ", item_category: "パンツ", value: 17000, image: "../broken_image.png" },
    { id: 35, brand: "ISSEYMIYAKE", item: "藍染シャツ", item_category: "シャツ", value: 22000, image: "../broken_image.png" },
];