import { Data } from "./data";

export const DATA: Data[] = [
    { id: 0, brand: "BLACK COMME DES GARCONS", item_name: "プリーツシャツ", item_category: "シャツ", value: 25000, image: "assets/broken_image.png" },
    { id: 1, brand: "BLACK COMME DES GARCONS", item_name: "シワ加工バルーンパンツ", item_category: "パンツ", value: 35000, image: "assets/broken_image.png" },
    { id: 2, brand: "BLACK COMME DES GARCONS", item_name: "ナイトトラック", item_category: "シューズ", value: 20000, image: "assets/broken_image.png" },
    { id: 3, brand: "LAD MUSICIAN", item_name: "靴下", item_category: "レッグウェア", value: 2000, image: "assets/broken_image.png" },
    { id: 4, brand: "LAD MUSICIAN", item_name: "靴下", item_category: "レッグウェア", value: 2000, image: "assets/broken_image.png" },
    { id: 5, brand: "used", item_name: "バルーンパンツ", item_category: "パンツ", value: 8000, image: "assets/broken_image.png" },
    { id: 6, brand: "BLACK COMME DES GARCONS", item_name: "シワ加工シャツ", item_category: "シャツ", value: 20000, image: "assets/broken_image.png" },
    { id: 7, brand: "used", item_name: "ストレートリブパンツ", item_category: "パンツ", value: 10000, image: "assets/broken_image.png" },
    { id: 8, brand: "used", item_name: "ロングチェスターコート", item_category: "アウター", value: 25000, image: "assets/broken_image.png" },
    { id: 9, brand: "used", item_name: "チェスターコート", item_category: "アウター", value: 24000, image: "assets/broken_image.png" },
    { id: 10, brand: "ANREALAGE", item_name: "ボールシャツ", item_category: "シャツ", value: 24000, image: "assets/broken_image.png" },
    { id: 11, brand: "ANREALAGE", item_name: "トートバッグ", item_category: "バッグ", value: 4000, image: "assets/broken_image.png" },
    { id: 12, brand: "used", item_name: "チェックボアブルゾン", item_category: "アウター", value: 20000, image: "assets/broken_image.png" },
    { id: 13, brand: "LAD MUSICIAN", item_name: "スカートワイドパンツ", item_category: "パンツ", value: 35000, image: "assets/broken_image.png" },
    { id: 14, brand: "CHRISTIAN DADA", item_name: "KARAKUSA Buckle Leather Belt", item_category: "ベルト", value: 14000, image: "assets/broken_image.png" },
    { id: 15, brand: "DR.MARTENS", item_name: "ダブルバックルレザーシューズ", item_category: "シューズ", value: 12000, image: "assets/broken_image.png" },
    { id: 16, brand: "BLACK COMME DES GARCONS", item_name: "墨ぶち撒けシャツ", item_category: "シャツ", value: 25000, image: "assets/broken_image.png" },
    { id: 17, brand: "ISSEYMIYAKE", item_name: "チャイナシャツ", item_category: "シャツ", value: 20000, image: "assets/broken_image.png" },
    { id: 18, brand: "LANVIN", item_name: "ストレートトラウザーズ", item_category: "パンツ", value: 20000, image: "assets/broken_image.png" },
    { id: 19, brand: "COMME DES GARCONS HOMME DEUX", item_name: "スタッズシャツ", item_category: "シャツ", value: 24000, image: "assets/broken_image.png" },
    { id: 20, brand: "YOHJI YAMAMOTO", item_name: "バックパッチワークジャケット", item_category: "ジャケット", value: 40000, image: "assets/broken_image.png" },
    { id: 21, brand: "used", item_name: "ジップパンクブルゾン", item_category: "ジャケット", value: 16000, image: "assets/broken_image.png" },
    { id: 22, brand: "LAD MUSICIAN", item_name: "幾何学カットソー", item_category: "Tシャツ/カットソー", value: 10000, image: "assets/broken_image.png" },
    { id: 23, brand: "LAD MUSICIAN", item_name: "グラフィカルカットソー", item_category: "Tシャツ/カットソー", value: 15000, image: "assets/broken_image.png" },
    { id: 24, brand: "BLACK COMME DES GARCONS", item_name: "ジップトラウザーズ", item_category: "パンツ", value: 53000, image: "assets/broken_image.png" },
    { id: 25, brand: "JULIUS", item_name: "プリントハイネックカットソー", item_category: "Tシャツ/カットソー", value: 15000, image: "assets/broken_image.png" },
    { id: 26, brand: "Y-3", item_name: "ワイドカーゴパンツ", item_category: "パンツ", value: 20000, image: "assets/broken_image.png" },
    { id: 27, brand: "used", item_name: "オーバーサイズデニムジャケット", item_category: "ジャケット", value: 14000, image: "assets/broken_image.png" },
    { id: 28, brand: "RAF SIMONS", item_name: "プリントオーバーサイズシャツ", item_category: "シャツ", value: 39000, image: "assets/broken_image.png" },
    { id: 29, brand: "MOSCHINO", item_name: "プリントジャケット", item_category: "ジャケット", value: 30000, image: "assets/broken_image.png" },
    { id: 30, brand: "DIOR HOMME", item_name: "レースアップブーツ", item_category: "シューズ", value: 51000, image: "assets/broken_image.png" },
    { id: 31, brand: "CHRISTIAN DADA", item_name: "バケットハット", item_category: "ハット/キャップ", value: 16000, image: "assets/broken_image.png" },
    { id: 32, brand: "CHRISTIAN DADA", item_name: "ダウントレンチ", item_category: "アウター", value: 120000, image: "assets/broken_image.png" },
    { id: 33, brand: "VIKTOR&ROLF", item_name: "メガネ", item_category: "アイウェア", value: 53000, image: "assets/broken_image.png" },
    { id: 34, brand: "used", item_name: "リアルレザーパンツ", item_category: "パンツ", value: 17000, image: "assets/broken_image.png" },
    { id: 35, brand: "ISSEYMIYAKE", item_name: "藍染シャツ", item_category: "シャツ", value: 22000, image: "assets/broken_image.png" },
    { id: 36, brand: "NIKE", item_name: "ナイトトラック", item_category: "シューズ", value: 20000, image: "assets/broken_image.png" },
    { id: 37, brand: "NILOS", item_name: "オーバーサイズカットソー", item_category: "Tシャツ/カットソー", value: 16000, image: "assets/broken_image.png" },
    { id: 38, brand: "BALENCIAGA", item_name: "ミリタリーコート", item_category: "アウター", value: 85600, image: "assets/broken_image.png" },
    { id: 39, brand: "VALENTINO", item_name: "デニムパンツ", item_category: "パンツ", value: 41800, image: "assets/broken_image.png" },
    { id: 40, brand: "3.1 Phillip Lim", item_name: "ハイブリッドニットコート", item_category: "アウター", value: 41800, image: "assets/broken_image.png" },
    { id: 41, brand: "Sacai", item_name: "LDWaffle", item_category: "シューズ", value: 31500, image: "assets/broken_image.png" },
    { id: 42, brand: "NIKE", item_name: "LDWaffle", item_category: "シューズ", value: 31500, image: "assets/broken_image.png" },
];